@echo off
rem GreaterNews morning run - scheduled daily. Writes today's verified content pack
rem AND auto-renders the finished card PNGs + videos into content\<date>\assets\.
cd /d C:\GreaterNews
echo ===== GreaterNews morning run started %date% %time% ===== >> C:\GreaterNews\content\morning-run.log
claude -p "Read C:\GreaterNews\GreaterNews_Master_Prompt.md and follow it strictly as the GreaterNews content engine. Do the Daily run now. Search the web for todays top stories in each bucket: Ghana politics 1-2, Ghana business 1, sports 1-2, entertainment 1, world 1-2, tech optional. Verify every story with two or more independent current sources and label single-source stories DEVELOPING. Check the files in C:\GreaterNews\content and posted_log.md first so no story repeats. Then write the story menu plus complete content packs for the top 5 stories in all output formats to a new file named C:\GreaterNews\content\greaternews_DATE.md where DATE is todays date in YYYY-MM-DD format. Include the source URLs you verified against. ALSO write a card spec file C:\GreaterNews\content\cards_DATE.json with this exact JSON shape: {\"date\":\"DATE\",\"cards\":[{\"slug\":\"kebab-case-story-slug\",\"template\":\"headline or quote or update or stat\",\"headline\":\"card headline max 9 words (for quote: the exact quote under 15 words; for stat: the label)\",\"subline\":\"one sentence of context under the headline (headline and update templates, else empty)\",\"highlight\":\"2-4 headline words to color, empty string for tragedy\",\"attribution\":\"speaker name and title (quote template only, else empty)\",\"chip\":\"UPDATE or DEVELOPING or BREAKING (update template only)\",\"statValue\":\"the number (stat template only, else empty)\",\"footer\":\"Source: X / Y\",\"dim\":0.3 to 0.6 higher for somber stories,\"formats\":[\"portrait\"],\"video\":true for the top story and stat cards else false,\"photoUrl\":null}]}. Use photoUrl ONLY for an image we verifiably hold rights to; otherwise null. ALSO write a publish queue C:\GreaterNews\content\queue_DATE.json with this exact shape: {\"date\":\"DATE\",\"items\":[{\"platform\":\"facebook or x\",\"status\":\"pending\",\"image\":\"DATE/assets/SLUG_4x5.png or null\",\"text\":\"the full post text for that platform from the pack\"}]} ordered strongest story first, with a facebook and an x item for each of the top 3 stories (X posts must be 280 characters or fewer). Do not post anything anywhere yourself. End the pack file with a list of any DEVELOPING stories that need follow-up." --allowedTools "Read,Write,Glob,Grep,WebSearch,WebFetch" >> C:\GreaterNews\content\morning-run.log 2>&1
echo ----- rendering card assets ----- >> C:\GreaterNews\content\morning-run.log
python C:\GreaterNews\scripts\render_assets.py >> C:\GreaterNews\content\morning-run.log 2>&1
echo ----- publish queue status ----- >> C:\GreaterNews\content\morning-run.log
python C:\GreaterNews\scripts\publish.py --dry-run >> C:\GreaterNews\content\morning-run.log 2>&1
echo ===== GreaterNews morning run finished %date% %time% ===== >> C:\GreaterNews\content\morning-run.log
